export const GET_ALL_CAUSES = 'GET_ALL_CAUSES'
export const GET_CAUSE = 'GET_CAUSE'
export const CAUSE_API_ERROR = 'CAUSE_API_ERROR'
export const UPDATE_LIKE_BUTTON = 'UPDATE_LIKE_BUTTON'
export const UPDATE_LIKE_USER_PENDING = 'UPDATE_LIKE_USER_PENDING'

export const GET_CAUSE_PENDING = 'GET_CAUSE_PENDING'
export const GET_CAUSES_PENDING = 'GET_CAUSES_PENDING'
export const CREATE_CAUSE_PENDING = 'CREATE_CAUSE_PENDING'