export const GET_ALL_CAUSES = 'GET_ALL_CAUSES'
export const GET_CAUSE = 'GET_CAUSE'
export const CAUSE_API_ERROR = 'CAUSE_API_ERROR'

export const GET_CAUSE_PENDING = 'GET_CAUSE_PENDING'
export const GET_CAUSES_PENDING = 'GET_CAUSES_PENDING'